### ISSUE TITLE
Moving to CMSSW 7_4_14

### ISSUE THREAD

**Issue by swertz** [cp3-llbb/TTAnalysis#12]
To be able to run over the latter part of 2015D (starting from run 258159) we need CMSSW >= 7414 (7415 is available). This then means also using the re-miniAOD of 2015D up to run 258159 (different GT, needs to be done separately): DoubleMuon and DoubleEG and MuonEG are available in DAS as of now.

Regarding MC, the following re-miniAOD are available:
- TT, TTW (W>lnu/qq), TTZ (Z>qq)
- singleTop (t- & s-channel 4f leptonDecay, tW 5f inclusive)
- DYJets to LL
- VV, WZZ

Which means that we can start using the re-miniAOD. Beside updating the analyzer so that the analyzers manager is also passed to TTAnalyzer::analize(), and swiching to redoJEC=false (since the new JEC is now included by default), is there anything else missing? Is the Framework ready?

**Comment by blinkseb** [comment]
framework should be ready, only one missing PR needs to be merged, otherwise we are good to go!

**Comment by swertz** [comment]
Great :) Anyway, since we need to implement @OlivierBondu's suggestion to circumvent 3D vectors, this production will have to wait...

**Comment by swertz** [comment]
Closed by #11
