### ISSUE TITLE
Types in Framework

### ISSUE THREAD

**Issue by AlexandreMertens** [cp3-llbb/TTAnalysis#21]
Could it be possible to include the structures from interface/Types.h in the Framework?

very good job BTW!

**Comment by swertz** [comment]
What exactly do you mean? I think the structures should stay analysis-specific (even if for now they are about the same in HH and TT)... If you want to re-use them for ZA, you can just copy the files along with Indices.h/cc and change the namespace ;)

**Comment by AlexandreMertens** [comment]
yep, just did it. Thanks!
