### ISSUE TITLE
Bug: "MissingParameter"

### ISSUE THREAD

**Issue by swertz** [cp3-llbb/TTAnalysis#31]
I'm getting the following failure when trying to run on MC (76X):

```
----- Begin Fatal Exception 04-Mar-2016 16:33:56 CET-----------------------
An exception of category 'Configuration' occurred while
   [0] Constructing the EventProcessor
   [1] Constructing module: class=SmearedPATJetProducer label='slimmedJetsSmeared'
Exception Message:
MissingParameter: Parameter 'dRmaxGenJetMatch' not found.
----- End Fatal Exception -------------------------------------------------
```

Not sure if this is related to the framework or if there is a problem with the TT configuration..

**Comment by swertz** [comment]
Works fine on data (which makes sens given the error)...

**Comment by BrieucF** [comment]
I just had the same earlier today (in 74X). Pulling the last version of the Framework is not enough because the installation recipe changed. I re-installed it following the new readme and it went fine.

**Comment by blinkseb** [comment]
Look at the recipe, there's new 'merge-topic' that are needed

**Comment by blinkseb** [comment]
This one in particular:

```
git cms-merge-topic blinkseb:smeared_jet_producer
```

**Comment by swertz** [comment]
Thanks, it's weird since I did reinstall the framework from scratch in 76X... I must have overlooked that line!

It works now.
