### ISSUE TITLE
Store matched GEN level information

### ISSUE THREAD

**Issue by swertz** [cp3-llbb/TTAnalysis#6]

**Comment by blinkseb** [comment]
See https://github.com/swertz/TTAnalysis/compare/secondRound...blinkseb:tt_gen

**Comment by swertz** [comment]
Awesome, thanks! :)

Just a question: did it still compile when removing https://github.com/swertz/TTAnalysis/compare/secondRound...blinkseb:tt_gen#diff-d127343f772c12c80a14c1cbf816741aL8 ? I had to add it because std::min( { } ) is only available in C++11...

Also, it's a bit of annoying copy paste, but can we also store DeltaPhi and DeltaEta between the tops and antitops?

**Comment by blinkseb** [comment]
Yep it compile fines, since CMSSW is built with C++11 since v6 :smile: 

I'll add DeltaPhi and DeltaEta too. Do you think we need also between the Bs?

**Comment by swertz** [comment]
Addressed by #11 but still a small bug when trying to identify the ttbar decay channel. @blinkseb taking a look.

**Comment by blinkseb** [comment]
Hopefully fixed by #14

**Comment by blinkseb** [comment]
Apparently #14 is not enough, reopening

**Comment by blinkseb** [comment]
And closed again by #17, for good this time :pray:
