### ISSUE TITLE
Store leptons in a smarted way

### ISSUE THREAD

**Issue by swertz** [cp3-llbb/TTAnalysis#7]
See https://github.com/cp3-llbb/HHAnalysis/issues/18

Currently working on something similar; it's almost done...

**Comment by swertz** [comment]
#9 shows the work in progress.

**Comment by blinkseb** [comment]
Will do today :+1:

**Comment by swertz** [comment]
Thanks :) It doesn't compile for the moment because storing structures is not finished, and dilepton categories need to be updated.

**Comment by swertz** [comment]
Closed by #11
